deleted seniors, request, and chapter
JumboCode/TheLegacyProject2 pull request #173
Opened 2024-04-25 02:28 UTC by nathan-j-edwards

# Description

- Delete the chapter itself 
- Delete all associated seniors
- Delete chapter request
- Remove chapter ID from every member 

## Issues

https://github.com/JumboCode/TheLegacyProject2/issues/155

## Screenshots

No user interface changes 

## Test

Submit new chapter request and accept. Add members, seniors, and files. Delete chapter and check database.

2024-04-25 04:04 UTC, nickbar01234 commented on src/components/AdminHomePage.tsx
> +            window.location.reload();
We should use `router` object. This can be imported from `useRouter`!

2024-04-25 04:19 UTC, nickbar01234 commented on src/app/api/chapter/[chapterId]/route.client.ts
> +export const DeleteChapter = async (chapterId: string) => {
nit: Use camel case.

2024-04-25 04:19 UTC, nickbar01234 commented on src/app/api/chapter/[chapterId]/route.client.ts
> +  console.log(json);
Don't forget to remove the console log!

2024-04-25 04:20 UTC, sburchfield33 requested changes
GJ!

2024-04-25 04:20 UTC, sburchfield33 commented on src/app/api/chapter/[chapterId]/route.schema.ts
> +  }),
These are not used in the route.ts

2024-04-25 04:20 UTC, sburchfield33 commented on src/app/api/chapter/[chapterId]/route.ts
> +  });
```suggestion
```

This can be removed because in theory the onDelete cascade should take care of this

2024-04-25 04:20 UTC, sburchfield33 commented on src/app/api/chapter/[chapterId]/route.ts
> +  });
1. Add a relation of userRequest to chapter
2. Add onDelete cascade so that this call isn't necessary

2024-04-25 04:20 UTC, sburchfield33 commented on src/app/api/chapter/[chapterId]/route.ts
> +  });
1. Add onDelete: setNull

2024-04-25 04:21 UTC, sburchfield33 commented on src/app/api/chapter/[chapterId]/route.ts
> +  });
To the user schema next to the onDelete

2024-04-25 04:38 UTC, sburchfield33 commented on src/app/api/chapter/[chapterId]/route.ts
> +  });
By doing this we can remove this deleteMany call

2024-04-25 04:38 UTC, sburchfield33 commented on src/app/api/chapter/[chapterId]/route.ts
> +  });
Also by doing this we can remove this update call

2024-04-25 06:53 UTC, nickbar01234 requested changes
Your changes are functionally correct! Echoing @sburchfield33 feedback, I think we can condensed the code a bit further. As mentioned, we want to reduce the number of API calls. This is important for a couple of reasons:

1. Less network traffic is usually better
2. Prisma handles **transaction** for us within 1 API call

In summary,

1. We can use `onDelete: Cascade` for `UserRequest`
2. Unset relationship on user side when a chapter is deleted. You may find this [doc helpful](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#disconnect-all-related-records).

2024-04-28 18:40 UTC, sburchfield33 reviewed
Looks good maybe look at my comments. I am a little confused about the ChapterRequest onDelete but otherwise looks good

2024-04-28 18:40 UTC, sburchfield33 commented on prisma/schema.prisma
> +
Is a chapterid field not necessary here?

2024-04-28 18:40 UTC, sburchfield33 commented on prisma/schema.prisma
> +  chapterRequest ChapterRequest @relation(fields: [chapterRequestId], references: [id], onDelete: Cascade)
Shouldn't the onDelete cascade be on the ChapterRequest field here? Wouldn't  the onDelete here just delete the chapter is the chapterrequest is deleted?

I assume what you are trying to do here is delete the ChapterRequest if the chapter is deleted so I believe the onDelete should be on the chapterrequest side.

2024-04-28 20:53 UTC, nickbar01234 approved these changes
Discussed with @sburchfield33! We're good to go.

2024-04-28 20:54 UTC, merged